<?php
if( function_exists('register_field_group') ):

register_field_group(array (
	'key' => 'group_acf_promoted-results',
	'title' => 'Promoted Results',
	'fields' => array (
		array (
			'key' => 'field_52fe37a94f99c',
			'label' => 'Result URL',
			'name' => 'result_url',
			'prefix' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'formatting' => 'html',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_53bd64ee9d1ad',
			'label' => 'A to Z index',
			'name' => 'a_to_z_index',
			'prefix' => '',
			'type' => 'checkbox',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				1 => 'Include in A to Z index?',
			),
			'default_value' => array (
				'' => '',
			),
			'layout' => 'horizontal',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'promoted_results',
				'order_no' => 0,
				'group_no' => 0,
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
	),
	'id' => 'acf_promoted-results',
	'local' => 'php',
));

register_field_group(array (
	'key' => 'group_551f0494e2163',
	'title' => 'Student Profiles',
	'fields' => array (
		array (
			'key' => 'field_551f04a052955',
			'label' => 'Class of',
			'name' => 'student_profile_class_of',
			'prefix' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_551f04b669a35',
			'label' => 'Program',
			'name' => 'student_profile_program',
			'prefix' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'profile',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

register_field_group(array (
	'key' => 'group_acf_sticky',
	'title' => 'Sticky',
	'fields' => array (
		array (
			'key' => 'field_537ced48a2ce6',
			'label' => 'Sticky this item',
			'name' => 'sticky',
			'prefix' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Sticky',
			'default_value' => 1,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'announcement',
				'order_no' => 0,
				'group_no' => 0,
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'billboard',
				'order_no' => 0,
				'group_no' => 1,
			),
		),
	),
	'menu_order' => 1,
	'position' => 'side',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
	),
	'id' => 'acf_sticky',
	'local' => 'php',
));

register_field_group(array (
	'key' => 'group_acf_announcement',
	'title' => 'Announcement',
	'fields' => array (
		array (
			'key' => 'field_5273e0d6627ef',
			'label' => 'URL',
			'name' => 'url',
			'prefix' => '',
			'type' => 'website',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'website_title' => 0,
			'output_format' => 1,
			'default_value' => '',
			'internal_link' => 0,
		),
		array (
			'key' => 'field_5273d8df144ef',
			'label' => 'Internal only',
			'name' => 'internal_only',
			'prefix' => '',
			'type' => 'checkbox',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				1 => 'Internal Only',
			),
			'default_value' => array (
				'' => '',
			),
			'layout' => 'vertical',
		),
		array (
			'key' => 'field_5274121ad05c0',
			'label' => 'Expiration Date',
			'name' => 'expiration_date',
			'prefix' => '',
			'type' => 'date_time_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'show_date' => 'true',
			'date_format' => 'yy-mm-dd',
			'time_format' => 'HH:mm',
			'show_week_number' => 'false',
			'picker' => 'slider',
			'save_as_timestamp' => 'false',
			'get_as_timestamp' => 'false',
		),
		array (
			'key' => 'field_53bd808628cda',
			'label' => 'Hide Nav',
			'name' => 'hide_nav',
			'prefix' => '',
			'type' => 'checkbox',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				1 => 'Hide Left Nav?',
			),
			'default_value' => array (
				'' => '',
			),
			'layout' => 'horizontal',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'announcement',
				'order_no' => 0,
				'group_no' => 0,
			),
		),
	),
	'menu_order' => 2,
	'position' => 'acf_after_title',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
	),
	'id' => 'acf_announcement',
	'local' => 'php',
));

register_field_group(array (
	'key' => 'group_acf_billboard',
	'title' => 'Billboard',
	'fields' => array (
		array (
			'key' => 'field_51d18a2f0e95c',
			'label' => 'Link',
			'name' => 'link',
			'prefix' => '',
			'type' => 'website',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'website_title' => 0,
			'output_format' => 1,
			'default_value' => '',
			'internal_link' => 0,
		),
		array (
			'key' => 'field_526ae41c37a73',
			'label' => 'Internal Only',
			'name' => 'internal_only',
			'prefix' => '',
			'type' => 'checkbox',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				1 => 'Internal Only',
			),
			'default_value' => array (
				'' => '',
			),
			'layout' => 'vertical',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'billboard',
				'order_no' => 0,
				'group_no' => 0,
			),
		),
	),
	'menu_order' => 3,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
	),
	'id' => 'acf_billboard',
	'local' => 'php',
));

register_field_group(array (
	'key' => 'group_acf_faculty-profiles',
	'title' => 'Faculty Profiles',
	'fields' => array (
		array (
			'key' => 'field_534556dc83901',
			'label' => 'Award Name',
			'name' => 'award_name',
			'prefix' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'formatting' => 'html',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_534556f083902',
			'label' => 'Award Honor',
			'name' => 'award_honor',
			'prefix' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'formatting' => 'html',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5214cff265257',
			'label' => 'More Info',
			'name' => 'more_info',
			'prefix' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'row_min' => '',
			'row_limit' => '',
			'layout' => 'row',
			'button_label' => 'Add Row',
			'min' => 0,
			'max' => 0,
			'sub_fields' => array (
				array (
					'key' => 'field_5214d00065258',
					'label' => 'Link Text',
					'name' => 'link_text',
					'prefix' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'html',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_5214d01065259',
					'label' => 'Link URL',
					'name' => 'link_url',
					'prefix' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'html',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'faculty_profile',
				'order_no' => 0,
				'group_no' => 0,
			),
		),
	),
	'menu_order' => 4,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
	),
	'id' => 'acf_faculty-profiles',
	'local' => 'php',
));

register_field_group(array (
	'key' => 'group_acf_giving-page-extras',
	'title' => 'Giving page extras',
	'fields' => array (
		array (
			'key' => 'field_52e7d38a0f064',
			'label' => 'Header text',
			'name' => 'header_text',
			'prefix' => '',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'toolbar' => 'full',
			'media_upload' => 0,
			'tabs' => 'all',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'giving-page.php',
				'order_no' => 0,
				'group_no' => 0,
			),
		),
	),
	'menu_order' => 5,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
	),
	'id' => 'acf_giving-page-extras',
	'local' => 'php',
));

register_field_group(array (
	'key' => 'group_acf_in-focus',
	'title' => 'In Focus',
	'fields' => array (
		array (
			'key' => 'field_5351884a9f959',
			'label' => 'External Link',
			'name' => 'external_link',
			'prefix' => '',
			'type' => 'website',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'website_title' => 1,
			'output_format' => 1,
			'default_value' => '',
			'internal_link' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'in_focus',
				'order_no' => 0,
				'group_no' => 0,
			),
		),
	),
	'menu_order' => 6,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
	),
	'id' => 'acf_in-focus',
	'local' => 'php',
));

register_field_group(array (
	'key' => 'group_acf_press',
	'title' => 'Press',
	'fields' => array (
		array (
			'key' => 'field_5273cfea28929',
			'label' => 'URL',
			'name' => 'url',
			'prefix' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'formatting' => 'none',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5273ce6644829',
			'label' => 'Source',
			'name' => 'source',
			'prefix' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'formatting' => 'html',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'media_mentions',
			),
		),
	),
	'menu_order' => 7,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

register_field_group(array (
	'key' => 'group_acf_locations',
	'title' => 'Locations',
	'fields' => array (
		array (
			'key' => 'field_52cf1d4ad4dbf',
			'label' => 'Location image',
			'name' => 'location_image',
			'prefix' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'preview_size' => 'map-img',
			'library' => 'all',
			'return_format' => 'id',
			'min_width' => 0,
			'min_height' => 0,
			'min_size' => 0,
			'max_width' => 0,
			'max_height' => 0,
			'max_size' => 0,
			'mime_types' => '',
		),
		array (
			'key' => 'field_524f29fd79223',
			'label' => 'Location',
			'name' => 'location',
			'prefix' => '',
			'type' => 'google_map',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'center_lat' => '',
			'center_lng' => '',
			'zoom' => '',
			'height' => '',
		),
		array (
			'key' => 'field_52a0fb7a8b392',
			'label' => 'Location Number',
			'name' => 'num',
			'prefix' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'formatting' => 'html',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'location',
			),
		),
	),
	'menu_order' => 8,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

register_field_group(array (
	'key' => 'group_acf_national-leaders',
	'title' => 'National Leaders',
	'fields' => array (
		array (
			'key' => 'field_52a0fb4d5f46c',
			'label' => 'Optional Link',
			'name' => 'nl-link',
			'prefix' => '',
			'type' => 'website',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'website_title' => 0,
			'output_format' => 1,
			'default_value' => '',
			'internal_link' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'spotlight',
				'order_no' => 0,
				'group_no' => 0,
			),
		),
	),
	'menu_order' => 9,
	'position' => 'acf_after_title',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
	),
	'id' => 'acf_national-leaders',
	'local' => 'php',
));

register_field_group(array (
	'key' => 'group_acf_news-releases',
	'title' => 'News Releases',
	'fields' => array (
		array (
			'key' => 'field_5273d2931a04c',
			'label' => 'URL',
			'name' => 'url',
			'prefix' => '',
			'type' => 'website',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'website_title' => 0,
			'output_format' => 1,
			'default_value' => '',
			'internal_link' => 0,
		),
		array (
			'key' => 'field_526ad43464149',
			'label' => 'Audio',
			'name' => 'audio',
			'prefix' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'http://mpaweb1.wustl.edu/XXXXXXXXXX',
			'prepend' => '',
			'append' => '',
			'formatting' => 'none',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_526562a5de521',
			'label' => 'Video',
			'name' => 'video',
			'prefix' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'http://www.youtube.com/watch?v=XXXXXXXXXXXXX',
			'prepend' => '',
			'append' => '',
			'formatting' => 'none',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_53bd8213f1b9a',
			'label' => 'Hide Nav',
			'name' => 'hide_nav',
			'prefix' => '',
			'type' => 'checkbox',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				1 => 'Hide Left Nav?',
			),
			'default_value' => array (
				'' => '',
			),
			'layout' => 'horizontal',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'news_releases',
				'order_no' => 0,
				'group_no' => 0,
			),
		),
	),
	'menu_order' => 10,
	'position' => 'acf_after_title',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
	),
	'id' => 'acf_news-releases',
	'local' => 'php',
));

register_field_group(array (
	'key' => 'group_acf_page-extras',
	'title' => 'Page extras',
	'fields' => array (
		array (
			'key' => 'field_5307f657576df',
			'label' => 'Special header',
			'name' => 'special_header',
			'prefix' => '',
			'type' => 'post_object',
			'instructions' => '"Breadcrumb" nav found above page title in Executive Management Fellowship section',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
				0 => 'page',
			),
			'taxonomy' => array (
			),
			'allow_null' => 1,
			'multiple' => 0,
			'return_format' => 'object',
			'ui' => 1,
		),
		array (
			'key' => 'field_526ed9af938eb',
			'label' => 'Nav menu title',
			'name' => 'nav_menu_title',
			'prefix' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'formatting' => 'html',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_526fde04dfc61',
			'label' => 'Hide in Nav',
			'name' => 'hide_in_nav',
			'prefix' => '',
			'type' => 'checkbox',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				1 => 'Hide in Nav?',
			),
			'default_value' => array (
				'' => '',
			),
			'layout' => 'horizontal',
		),
		array (
			'key' => 'field_53bd58104efb4',
			'label' => 'Hide Nav',
			'name' => 'hide_nav',
			'prefix' => '',
			'type' => 'checkbox',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				1 => 'Hide Left Nav?',
			),
			'default_value' => array (
				'' => '',
			),
			'layout' => 'horizontal',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
				'order_no' => 0,
				'group_no' => 0,
			),
		),
	),
	'menu_order' => 11,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
	),
	'id' => 'acf_page-extras',
	'local' => 'php',
));

register_field_group(array (
	'key' => 'group_acf_promoted-result',
	'title' => 'Promoted Result',
	'fields' => array (
		array (
			'key' => 'field_52fe3b7e06d4d',
			'label' => 'Result source',
			'name' => 'result_source',
			'prefix' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'formatting' => 'html',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_52fe3291799e2',
			'label' => 'Promoted Result Terms',
			'name' => 'promoted_result_terms',
			'prefix' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'row_min' => '',
			'row_limit' => '',
			'layout' => 'table',
			'button_label' => 'Add Row',
			'min' => 0,
			'max' => 0,
			'sub_fields' => array (
				array (
					'key' => 'field_52fe32ac799e3',
					'label' => 'Promoted result term',
					'name' => 'promoted_result_term',
					'prefix' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'html',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
				'order_no' => 0,
				'group_no' => 0,
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
				'order_no' => 0,
				'group_no' => 1,
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'location',
				'order_no' => 0,
				'group_no' => 2,
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'news_releases',
				'order_no' => 0,
				'group_no' => 3,
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'media_mentions',
				'order_no' => 0,
				'group_no' => 4,
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'in_the_news',
				'order_no' => 0,
				'group_no' => 5,
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'billboard',
				'order_no' => 0,
				'group_no' => 6,
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'announcement',
				'order_no' => 0,
				'group_no' => 7,
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'spotlight',
				'order_no' => 0,
				'group_no' => 8,
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'research_news',
				'order_no' => 0,
				'group_no' => 9,
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'in_focus',
				'order_no' => 0,
				'group_no' => 10,
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'faculty_profile',
				'order_no' => 0,
				'group_no' => 11,
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'promoted_results',
				'order_no' => 0,
				'group_no' => 12,
			),
		),
	),
	'menu_order' => 12,
	'position' => 'side',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
	),
	'id' => 'acf_promoted-result',
	'local' => 'php',
));

register_field_group(array (
	'key' => 'group_acf_research-news',
	'title' => 'Research News',
	'fields' => array (
		array (
			'key' => 'field_5321d99f086fc',
			'label' => 'Author',
			'name' => 'author',
			'prefix' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Washington University School of Medicine',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'formatting' => 'html',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'research_news',
				'order_no' => 0,
				'group_no' => 0,
			),
		),
	),
	'menu_order' => 13,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
	),
	'id' => 'acf_research-news',
	'local' => 'php',
));

register_field_group(array (
	'key' => 'group_acf_sidebar',
	'title' => 'Sidebar',
	'fields' => array (
		array (
			'key' => 'field_526ad52c059e3',
			'label' => 'Right Sidebars',
			'name' => 'sidebars',
			'prefix' => '',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'button_label' => 'Add Sidebar',
			'min' => '',
			'max' => '',
			'layouts' => array (
				array (
					'key' => '54bfe34723e88',
					'name' => 'default',
					'label' => 'Related Links',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_526ad66326cd9',
							'label' => 'Sidebar Title',
							'name' => 'sidebar_title',
							'prefix' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'formatting' => 'html',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_534c10c04fa5c',
							'label' => 'Text',
							'name' => 'sidebar_text',
							'prefix' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'formatting' => 'html',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_526ad66e26cda',
							'label' => 'Link',
							'name' => 'sidebar_links',
							'prefix' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'row_min' => '',
							'row_limit' => '',
							'layout' => 'row',
							'button_label' => 'Add Row',
							'min' => 0,
							'max' => 0,
							'sub_fields' => array (
								array (
									'key' => 'field_526ad67d26cdb',
									'label' => 'Sidebar Link',
									'name' => 'sidebar_link',
									'prefix' => '',
									'type' => 'website',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'website_title' => 1,
									'output_format' => 1,
									'default_value' => '',
									'internal_link' => 0,
								),
								array (
									'key' => 'field_534c4c809befe',
									'label' => 'Description',
									'name' => 'description',
									'prefix' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'formatting' => 'html',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '54bfe34723f29',
					'name' => 'image_&_text',
					'label' => 'Image & Text',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_534c1180fbb99',
							'label' => 'Image',
							'name' => 'image',
							'prefix' => '',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'preview_size' => 'medium',
							'library' => 'all',
							'return_format' => 'id',
							'min_width' => 0,
							'min_height' => 0,
							'min_size' => 0,
							'max_width' => 0,
							'max_height' => 0,
							'max_size' => 0,
							'mime_types' => '',
						),
						array (
							'key' => 'field_534c1199fbb9a',
							'label' => 'Title',
							'name' => 'title',
							'prefix' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'formatting' => 'html',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_534c11a5fbb9b',
							'label' => 'Text',
							'name' => 'text',
							'prefix' => '',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'toolbar' => 'basic',
							'media_upload' => 0,
							'tabs' => 'all',
						),
						array (
							'key' => 'field_534c11d3fbb9c',
							'label' => 'Link',
							'name' => 'link',
							'prefix' => '',
							'type' => 'website',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'website_title' => 1,
							'output_format' => 1,
							'default_value' => '',
							'internal_link' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '54bfe34723fcd',
					'name' => 'single',
					'label' => 'Single Link',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_526ad6c326cdd',
							'label' => 'Single Link',
							'name' => 'single_link',
							'prefix' => '',
							'type' => 'website',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'website_title' => 1,
							'output_format' => 1,
							'default_value' => '',
							'internal_link' => 0,
						),
						array (
							'key' => 'field_534d8f5510564',
							'label' => 'Style',
							'name' => 'single_link_style',
							'prefix' => '',
							'type' => 'text',
							'instructions' => 'Styles to be applied to the link',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'formatting' => 'html',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '54bfe347240c0',
					'name' => 'outlook',
					'label' => 'Outlook Option',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_526ad764494dc',
							'label' => 'Outlook Issue URL',
							'name' => 'outlook_issue_url',
							'prefix' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 'http://outlook.wustl.edu',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'formatting' => 'none',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_526ad77b494dd',
							'label' => 'Outlook Thumbnail',
							'name' => 'outlook_thumbnail',
							'prefix' => '',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'preview_size' => 'outlook-thumb',
							'library' => 'all',
							'return_format' => 'url',
							'min_width' => 0,
							'min_height' => 0,
							'min_size' => 0,
							'max_width' => 0,
							'max_height' => 0,
							'max_size' => 0,
							'mime_types' => '',
						),
						array (
							'key' => 'field_526ad793494de',
							'label' => 'Outlook Title',
							'name' => 'outlook_title',
							'prefix' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'formatting' => 'html',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_526ad79f494df',
							'label' => 'Outlook Tease',
							'name' => 'outlook_tease',
							'prefix' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'formatting' => 'html',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '54bfe34724164',
					'name' => 'connect',
					'label' => 'Connect with us',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_526ad7c4494e1',
							'label' => 'Connect with us Title',
							'name' => 'connect_title',
							'prefix' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 'Connect with us',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'formatting' => 'html',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_526ad7dc494e2',
							'label' => 'Connect with us Buttons',
							'name' => 'connect_buttons',
							'prefix' => '',
							'type' => 'checkbox',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'fb' => 'Facebook',
								'twitter' => 'Twitter',
								'in' => 'LinkedIn',
								'youtube' => 'Youtube',
								'rss' => 'RSS',
							),
							'default_value' => array (
								'' => '',
							),
							'layout' => 'vertical',
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '54bfe347241f9',
					'name' => 'heart',
					'label' => 'Heart/Vascular',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_526ad85ccbe7c',
							'label' => 'Heart title',
							'name' => 'heart_title',
							'prefix' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 'Find a Heart Specialist',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'formatting' => 'html',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_526ad86ccbe7d',
							'label' => 'Heart subtitle',
							'name' => 'heart_subtitle',
							'prefix' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 'To schedule an appointment with a Washington University heart specialist',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'formatting' => 'html',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_526ad882cbe7e',
							'label' => 'Heart Links',
							'name' => 'heart_links',
							'prefix' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'row_min' => '',
							'row_limit' => '',
							'layout' => 'table',
							'button_label' => 'Add Row',
							'min' => 0,
							'max' => 0,
							'sub_fields' => array (
								array (
									'key' => 'field_526ad88acbe7f',
									'label' => 'Heart Link',
									'name' => 'heart_link',
									'prefix' => '',
									'type' => 'website',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'website_title' => 1,
									'output_format' => 1,
									'default_value' => '',
									'internal_link' => 0,
								),
								array (
									'key' => 'field_526ad898cbe80',
									'label' => 'Heart Link Phone',
									'name' => 'heart_link_phone',
									'prefix' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'formatting' => 'html',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '54bfe34724294',
					'name' => 'one_off',
					'label' => 'One-off',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_5279311ab7bd6',
							'label' => 'Raw HTML',
							'name' => 'raw_html',
							'prefix' => '',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'toolbar' => 'full',
							'media_upload' => 1,
							'tabs' => 'all',
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '54bfe34724382',
					'name' => 'announcements',
					'label' => 'Announcements',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_534d981e9fb89',
							'label' => 'Number of announcements to show',
							'name' => 'number_to_show',
							'prefix' => '',
							'type' => 'number',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 6,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'min' => 1,
							'max' => '',
							'step' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
			),
		),
		array (
			'key' => 'field_525ea7532a560',
			'label' => 'Sidebar Examples',
			'name' => '',
			'prefix' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '<img src=\'/wp-content/themes/medicine/_/img/sidebars.jpg\'>',
			'esc_html' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'announcement',
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'news_releases',
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'research_news',
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'profile',
			),
		),
	),
	'menu_order' => 14,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

register_field_group(array (
	'key' => 'group_acf_admin-extras',
	'title' => 'Admin Extras',
	'fields' => array (
		array (
			'key' => 'field_534e9b7ac7d36',
			'label' => 'Page-specific CSS',
			'name' => 'page_specific_css',
			'prefix' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_534e9ba7c7d37',
			'label' => 'Page-specific JS',
			'name' => 'page_specific_js',
			'prefix' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'current_user_role',
				'operator' => '==',
				'value' => 'administrator',
				'order_no' => 0,
				'group_no' => 0,
			),
		),
	),
	'menu_order' => 999,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
	),
	'id' => 'acf_admin-extras',
	'local' => 'php',
));

endif;